import { GoogleGenAI, Modality, Type, GenerateContentResponse } from "@google/genai";
import { UploadedImage, StickerIdea } from '../types';
import { v4 as uuidv4 } from 'uuid';

// FIX: Initialize GoogleGenAI with apiKey from environment variables.
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY! });

const imageGenerationModel = 'gemini-2.5-flash-image';
const textModel = 'gemini-2.5-pro'; // for complex reasoning like generating ideas
const fastTextModel = 'gemini-2.5-flash'; // for simple tasks like refining prompts

// Helper to convert base64 to a part for the Gemini API
const fileToGenerativePart = (base64Data: string) => {
    // remove "data:image/png;base64," prefix
    const data = base64Data.split(',')[1];
    const mimeType = base64Data.match(/:(.*?);/)?.[1] ?? 'image/png';
    return {
        inlineData: {
            data,
            mimeType,
        },
    };
};

export const generateImage = async (prompt: string, referenceImages: UploadedImage[], stylePreviewImage?: string | null): Promise<string> => {
    // Prioritize the style preview image for consistency
    const imageParts = stylePreviewImage 
        ? [fileToGenerativePart(stylePreviewImage)]
        : referenceImages.map(img => fileToGenerativePart(img.base64));

    try {
        const response: GenerateContentResponse = await ai.models.generateContent({
            model: imageGenerationModel,
            contents: {
                parts: [
                    ...imageParts,
                    { text: prompt },
                ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });

        // FIX: Check for prompt feedback and block reasons first for more specific errors.
        if (response.promptFeedback?.blockReason) {
            const reason = response.promptFeedback.blockReason;
            const message = response.promptFeedback.blockReasonMessage || 'No specific message.';
            console.error(`Image generation blocked. Reason: ${reason}. Message: ${message}`);
            throw new Error(`Image generation blocked due to safety policies. Please try a different prompt or character image.`);
        }

        for (const part of response.candidates?.[0]?.content?.parts || []) {
            if (part.inlineData) {
                const mimeType = part.inlineData.mimeType;
                const base64ImageBytes: string = part.inlineData.data;
                return `data:${mimeType};base64,${base64ImageBytes}`;
            }
        }
        
        // This happens if the API call succeeds but returns no image data and no block reason.
        console.error("API response did not contain an image:", response);
        throw new Error("No image was generated by the API.");
    } catch (error: any) {
        console.error("Error during image generation API call:", error);
        
        // Improved rate limit error detection
        const errorMessage = (error?.message || '').toString();
        let errorJson;
        try {
            errorJson = JSON.parse(errorMessage);
        } catch (e) {
            // Not a JSON string
        }

        if (errorMessage.includes('RESOURCE_EXHAUSTED') || errorJson?.error?.status === 'RESOURCE_EXHAUSTED' || errorJson?.error?.code === 429) {
            throw new Error("API rate limit exceeded. Please wait a moment and try again.");
        }

        // Re-throw specific errors, otherwise provide a general one.
        if (errorMessage.startsWith("Image generation blocked") || errorMessage.startsWith("No image was generated")) {
            throw error;
        }
        throw new Error("Failed to generate image. A network or API error occurred. Please try again.");
    }
};

export const getInspirationFromImages = async (referenceImages: UploadedImage[], language: string): Promise<string[]> => {
    const prompt = `
        You are a creative sticker planner. Based on the user's uploaded images, come up with 3 suitable and interesting sticker themes.
        The themes should be short, appealing, and natural for speakers of ${language}.
        Respond ONLY with a valid JSON array of 3 theme strings.
    `;
    const imageParts = referenceImages.map(img => fileToGenerativePart(img.base64));

    try {
        const response = await ai.models.generateContent({
            model: fastTextModel,
            contents: { parts: [...imageParts, { text: prompt }] },
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.ARRAY,
                    items: { type: Type.STRING },
                    description: "An array of 3 creative sticker theme suggestions."
                }
            }
        });

        const jsonStr = response.text.trim();
        return JSON.parse(jsonStr);
    } catch (error) {
        console.error("Failed to get inspiration from images:", error);
        throw new Error("Failed to get inspiration from images.");
    }
};


export const generateStickerIdeas = async (
    theme: string,
    characterDescription: string,
    count: number,
    language: string, // e.g., "Traditional Chinese"
    withText: boolean
): Promise<StickerIdea[]> => {
    const prompt = `
        You are a creative assistant for generating LINE sticker ideas.
        Based on the theme "${theme}" and the character description "${characterDescription}", generate ${count} unique, fun, and expressive sticker ideas.
        
        For each idea, provide a JSON object with three fields:
        1. "text": A short, user-facing description of the sticker idea. This MUST be in ${language}.
        2. "base": A concise, descriptive phrase in **English** detailing the character's action or expression. This is for the image generation AI. Example: "a cat waving goodbye sadly".
        3. "memeText": A very short (1-7 words) text to be placed *on* the sticker image. This MUST be in ${language}. If the idea is purely visual and doesn't need text, this must be an empty string.

        ${withText ? 'Most ideas should include text.' : 'All ideas should be purely visual; memeText must be an empty string for all.'}

        Respond ONLY with a valid JSON array of these objects.
    `;

    try {
        const response = await ai.models.generateContent({
            model: textModel,
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.ARRAY,
                    items: {
                        type: Type.OBJECT,
                        properties: {
                            text: { type: Type.STRING, description: `User-facing description of the idea in ${language}.` },
                            base: { type: Type.STRING, description: "Description for the image AI in English." },
                            memeText: { type: Type.STRING, description: `Short text for the sticker in ${language}.` }
                        },
                        required: ['text', 'base', 'memeText']
                    }
                }
            }
        });
        
        const jsonStr = response.text.trim();
        const ideas: Omit<StickerIdea, 'id'>[] = JSON.parse(jsonStr);
        return ideas.map(idea => ({ ...idea, id: uuidv4() }));
    } catch (error) {
        console.error("Error generating sticker ideas:", error);
        throw new Error("Failed to generate sticker ideas. Please try a different theme.");
    }
};

export const translateAndRefinePrompt = async (originalPrompt: string, userRequest: string): Promise<string> => {
    const prompt = `
        You are a prompt engineering assistant. Your task is to refine an existing image generation prompt based on a user's request.
        The user wants to modify an image that was generated with the following prompt:
        ---
        ORIGINAL PROMPT:
        ${originalPrompt}
        ---
        
        The user's modification request is: "${userRequest}".
        
        Analyze the original prompt and the user's request. Modify ONLY the relevant parts of the original prompt (like **Core Idea**, **Text**, or **Character Details**) to reflect the user's request.
        Do not change the core style, format, or outline instructions unless specifically asked.
        Output ONLY the new, complete, and refined prompt. Do not add any explanation or preamble.
    `;

    try {
        const response = await ai.models.generateContent({
            model: fastTextModel,
            contents: prompt,
        });
        return response.text.trim();
    } catch (error) {
        console.error("Error refining prompt:", error);
        throw new Error("Failed to refine prompt.");
    }
};

export const generateHashtags = async (ideaText: string, language: string): Promise<string[]> => {
    const prompt = `Based on this sticker idea: "${ideaText}", generate 3 to 5 relevant keyword tags suitable for the LINE Sticker Shop. The tags MUST be in ${language}. Respond ONLY with a JSON array of strings, do not include the '#' symbol.`;
    try {
        const response = await ai.models.generateContent({
            model: fastTextModel,
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.ARRAY,
                    items: { type: Type.STRING },
                    description: `An array of 3-5 keyword tags in ${language}.`
                }
            }
        });
        const jsonStr = response.text.trim();
        return JSON.parse(jsonStr);
    } catch (error) {
        console.error("Failed to generate hashtags:", error);
        return []; // Return empty array on failure
    }
};

export const generateStoreInfo = async (theme: string, ideaTexts: string[], language: string): Promise<{ title: string; description: string }> => {
    const prompt = `Based on the sticker theme "${theme}" and the list of ideas "${ideaTexts.join(', ')}", generate a suitable "title" and "description" for the LINE Creators Market. The title should be short and creative, and the description should vividly describe the sticker pack's features. Both title and description MUST be in ${language}.`;
    try {
        const response = await ai.models.generateContent({
            model: fastTextModel,
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: {
                    type: Type.OBJECT,
                    properties: {
                        title: { type: Type.STRING },
                        description: { type: Type.STRING }
                    },
                    required: ["title", "description"]
                }
            }
        });
        const jsonStr = response.text.trim();
        return JSON.parse(jsonStr);
    } catch (error) {
        console.error("Failed to generate store info:", error);
        return { title: "My Creative Sticker Pack", description: "A vibrant and fun sticker pack for daily chats!" };
    }
};